- name: Set Password
  hosts: all
  become: true

  tasks:
  - name: Set passwd
    user:
      name: pravin
      update_password: always
      #password: abcd123 # this will give error
      password: "{{'abcd12345' | password_hash('sha512', 'mysecretcode')}}"