- name: Firewall changes
  hosts: all
  become: true

  tasks:
    - name: Enable a service in firewalld
      firewalld:
        port: 80/tcp
        permanent: true
        state: disabled

    - name: Reload the firewalld
      service:
        name: firewalld
        state: reloaded



        