- name: User Mgm
  hosts: all
  become: true

  tasks:
    - name: User Creation
      user:
        name: "{{ item }}"
        comment: new user adding for QA Team
        shell: /bin/bash
      loop:
        - Raju
        - Sham
        - Baburao